name: Download and Commit Suricata Rules

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a medianoche UTC
  workflow_dispatch:  # Permite ejecutar manualmente el workflow

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Configure SSH
      run: |
        # Configura el agente SSH y añade la clave privada
        mkdir -p ~/.ssh
        echo "${{ secrets.SSHKEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSHKEY }}  # Usa la clave SSH privada

    - name: Download Suricata Rules
      run: |
        wget https://rules.pawpatrules.fr/suricata/paw-patrules.tar.gz -O paw-patrules.tar.gz

    - name: Extract tar.gz
      run: |
        tar -xzf paw-patrules.tar.gz
        ls ./  # Lista el contenido para verificar la extracción

    - name: Move rules to repository
      run: |
        mv rules/*.rules ./  # Asegúrate de que la ruta sea correcta

    - name: Commit changes
      run: |
        git config --global user.name "Manuel"
        git config --global user.email "manuelalberto.gorrin@gmail.com"
        git add *.rules
        git commit -m "Update Suricata rules [skip ci]"
        git push origin main  # Asegúrate de usar la rama correcta
