name: Download and Commit Suricata Rules

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSHKEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSHKEY }}

    - name: Download Suricata Rules
      run: |
        wget https://rules.pawpatrules.fr/suricata/paw-patrules.tar.gz -O paw-patrules.tar.gz

    - name: Extract tar.gz
      run: |
        tar -xzf paw-patrules.tar.gz

    - name: Move rules to repository
      run: |
        mv rules/*.rules ./

    - name: Cleanup temporary files  # <-- Limpieza añadida
      run: |
        rm paw-patrules.tar.gz
        rm -rf rules/

    - name: Commit changes
      run: |
        git config --global user.name "Manuel"
        git config --global user.email "manuelalberto.gorrin@gmail.com"
        git add *.rules

        # Verificar cambios antes de commit
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update Suricata rules [skip ci]"
          git push origin main
        else
          echo "No hay cambios para confirmar."
        fi
